name: random_features

channels:
  - conda-forge

dependencies:
  - numpy=1.20.3
  - numpy-base=1.18.5
  - scipy=1.5.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - pytorch=1.8.0
  - torchvision=0.9.0
  - gdown=3.13.0
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - dask=2021.6.0
  - dask-core=2021.6.0
  - jupyterlab=3.0.16
