name: random_features

channels:
  - conda-forge

dependencies:
  - numpy
  - numpy-base
  - scipy
  - matplotlib
  - matplotlib-base
  - pytorch
  - torchvision
  - gdown
  - scikit-image
  - scikit-learn
  - dask
