name: random_features

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - numpy=1.20.2=py38h4b4dc7a_0
  - numpy-base=1.20.2=py38he0bd621_0
  - scipy=1.6.2=py38hd5f7400_1
  - matplotlib=3.4.2=py38h50d1736_0
  - matplotlib-base=3.4.2=py38h6152e83_0
  - pytorch=1.8.0=py3.8_0
  - torchaudio=0.8.0=py38
  - torchvision=0.9.0=py38_cpu
  - gdown=3.13.0=pyhd8ed1ab_0
  - scikit-image=0.18.1=py38he9f00de_0
  - scikit-learn=0.24.2=py38hb2f4e1b_0
  - dask=2.30.0
  - python-dotenv
